language: python
python:
- 3.6
- 3.5
- 3.4
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: HintikkaKimmo
  password:
    secure: XAQbeOnH7jrakYSygE4J7E6jAnR0wBKauqWSRSuCHcl+LWxZG8keBERQJjXW4pnBK1SGgD/DZFlBuJ5o8ffVeD9xuG6AYwPOiWRddDhfVNwS6JnhMDb/wY5+fVHY7RTJJbtn/GJx37ojktLPid98iAvHNyfhOcTUDecPbFNfjE4HSOuFmEGuxqUMmzeDy8kDjhjzmFcKrQ2f05ajG/syoCFhoQdIf4D99v79pwa24BT0Iw7d1l3NQwKdiaoHO0XhGIsVDwmZtZcAFxuKRTzfTvq63n8Pj+8qqzWzMWJzfbwrUQKSTSL7qjV6TIFSZ1s9yh/Os2yQNcAhgNvtEqWFw21tuH7MnbZKTcyG4BDyC+kjihnxllppQbBtav6IZS3tEkwnR6ym/b08wH0A1Dpx9rAzqsDqlgCWTlavURPamwf+NpX0m77yW8bToVOGq2F6dAHw6TDMLInB2SVCpRWU6TC1ZNkKIrocrhav+5XQ7a07P2Dwt66IidqJawrdUBgrPQ65p2vpPc7IEwvWQQk8Ai3WSfdMZklV6NV9GsOW9r2o63dvQAXnNYqGrh+GtEpUVVI5YEMZPN4IKiMPIJop/K85AzvgP8SFSi9nSYr2V6KqvNUcWtTGTD0GJpClrRr9hOD/53rT8CjWvOk5NFcA612DbuNUyKElX8NK/eu3Nz4=
  on:
    tags: true
    repo: HintikkaKimmo/surebet
    python: 3.6
